model:
  arch: medlvlm
  model_type: pretrain
  max_txt_len: 1024
  image_size: 224
  end_sym: "</s>"
  vision_model: "biomed_clip"
  audio_model: "whisper"
  language_model: "meta-llama/Llama-2-7b-chat-hf"
  ckpt: "../Minigpt_Med_mainNew_global/LVLM-Med/medlvlm/Result/biomedClipLamaVindata-global/20240705222/checkpoint_9.pth"
  use_grad_checkpoint: True
  chat_template: True
  low_resource: True
  lora_r: 64
  lora_alpha: 16
  bits: 8
  # freeze_vision: False
  # freeze_audio: False
  
datasets:
  audio_train:
    batch_size: 4
    audio_processor: 
      train:
        name: 'whisper_processor'
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10
    
run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 2
  num_workers: 2
  warmup_steps: 1000
  iters_per_epoch: 3718

  seed: 42
  output_dir: "Hanh/Test_biomed_clip"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False

  wandb_log: True
  wandb_token: "e7134de62fe8b5b393083a97985006950575f545"
  job_name: bioclip-llama


