model:
  arch: silvar
  model_type: pretrain
  max_txt_len: 1024
  image_size: 224
  end_sym: "</s>"
  vision_model: "biomed_clip"
  audio_model: "whisper"
  language_model: "meta-llama/Meta-Llama-3-8B"
  ckpt: path/to/checkpoint
  use_grad_checkpoint: True
  chat_template: True
  low_resource: True
  lora_r: 64
  lora_alpha: 16
  bits: 8
  # freeze_vision: False For training end-to-end
  # freeze_audio: False For training end-to-end
  
datasets:
  audio_train:
    batch_size: 4
    audio_processor: 
      train:
        name: 'whisper_processor'
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10
    build_info:
      image_path: /train/images 
      ann_path: /train/train.json
      audio_path: /train/audio_wav

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 20
  num_workers: 2
  warmup_steps: 1000
  iters_per_epoch: 75

  seed: 42
  output_dir: path/to/output/directory

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False

  wandb_log: True
  wandb_token: "your-wandb-token"
  job_name: Silvar_audio


