model:
  arch: OmniMod
  model_type: pretrain
  max_txt_len: 1024
  image_size: 224
  end_sym: "</s>"
  vision_model: "biomed_clip"
  audio_model: "whisper"
  language_model: meta-llama/Llama-3.1-8B
  ckpt: OmniMod/Results/combined_new_OmniMedVQA/20250204224/checkpoint_8.pth
  use_grad_checkpoint: True
  chat_template: True
  low_resource: True
  lora_r: 64
  lora_alpha: 16
  bits: 8
  freeze_vision: False
  freeze_audio: False
  
datasets:
  audio_train:
    batch_size: 4
    audio_processor: 
      train:
        name: 'whisper_processor'
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10
    build_info: 
      image_path: ../../MedTrinity-25M/Data/slake/Slake/Abnormal_Ours/train/imgs_train_abnormal
      ann_path: ../../MedTrinity-25M/Data/slake/Slake/Abnormal_Ours/train/dataset_unique_abnormal.json
      audio_path: ../../MedTrinity-25M/Data/slake/Slake/Abnormal_Ours/train/audio_wav
run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 20
  num_workers: 2
  warmup_steps: 1000
  iters_per_epoch: 180

  seed: 42
  output_dir: "Results/abnormal_OmniMedVQA_llama31"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: False

  wandb_log: True
  wandb_token: "e7134de62fe8b5b393083a97985006950575f545"
  job_name: abnormal_OmniMedVQA_llama31


