model:
  arch: OmniMod

  # vision encoder
  vision_model: "eva_clip_g"
  image_size: 448
  drop_path_rate: 0
  use_grad_checkpoint: False
  precision: "fp16"
  freeze_vision: True

  # generation configs
  prompt: ""

  language_model: "please set this value to the path of language model"
  lora_r: 64
  lora_alpha: 16


preprocess:
    audio_processor: 
        train:
          name: 'whisper_processor'
    vis_processor:
        train:
          name: "videomae_processor"
          image_size: 448
        eval:
          name: "videomae_processor"
          image_size: 448
    text_processor:
        train:
          name: "blip_caption"
        eval:
          name: "blip_caption"